version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodata:/data/db

  init-mongo:
    image: python:3.9
    container_name: init-mongo
    depends_on:
      - mongodb
    volumes:
      - ./mongo/init:/app/init
    working_dir: /app/init
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=core
    entrypoint: ["python", "script.py"]

  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgresdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak 
      - KC_DB_PASSWORD=keycloak

      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false

      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin 
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/imports/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres

volumes:
  mongodata:
    external: true
  postgresdata:
    external: true

networks:
  default:
    external: true
    name: infrastructure_network